### ISSUE TITLE
Downloading ripgrep failed

### ISSUE THREAD

**Issue by slidoooor** [microsoft/ripgrep-prebuilt#17]
I'm having some problems with yarn vscode and it looks like it's because I'm using a proxy, do you have any clues?

error /vscode/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /vscode/node_modules/vscode-ripgrep
Output:
Finding release for v13.0.0-4
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-4
Deleting invalid download cache
Downloading ripgrep failed: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

**Comment by roblourens** [comment]
Should be fixed in version 1.14.2 of vscode-ripgrep (just published)

https://github.com/microsoft/vscode-ripgrep/issues/26

**Comment by slidoooor** [comment]
> 应该在 @vscode/ripgrep 的 1.14.2 版本中修复（刚刚发布）
> 
> [微软/vscode-ripgrep#26](https://github.com/microsoft/vscode-ripgrep/issues/26)

thanks!

**Comment by slidoooor** [comment]
> Should be fixed in version 1.14.2 of @vscode/ripgrep (just published)
> 
> [microsoft/vscode-ripgrep#26](https://github.com/microsoft/vscode-ripgrep/issues/26)

thanks!

**Comment by slidoooor** [comment]
It doesn't seem to be working for my computer, I still have the same prompt

**Comment by roblourens** [comment]
Which version of node are you using? Does it work with 14.x? And you have 1.14.2 of the npm module?

**Comment by slidoooor** [comment]
> Which version of node are you using? Does it work with 14.x? And you have 1.14.2 of the npm module?

node is 16.13.2, Is it possible that the version is too high?

**Comment by roblourens** [comment]
In microsoft/vscode-ripgrep#26 it was claimed that version of node would have this issue. It should have been fixed but I couldn't repro the issue to confirm. 

Are you sure you have 1.14.2 of the npm module?

**Comment by weartist** [comment]
> In [microsoft/vscode-ripgrep#26](https://github.com/microsoft/vscode-ripgrep/issues/26) it was claimed that version of node would have this issue. It should have been fixed but I couldn't repro the issue to confirm.
> 
> Are you sure you have 1.14.2 of the npm module?

yes and "https-proxy-agent": "^5.0.0",

**Comment by roblourens** [comment]
Thanks for checking. I will reopen the original issue.
